### PR TITLE
Course Registration ERD Diagram

### PR DESCRIPTION
**Pull request by CMUboy**
@mel-quark The diagram represents an ERD diagram for an online course registration system. There is a many-to-one relationship between Enrollment and Student and a many-to-one relationship between Enrollment and Course. In essence, there is a many-to-many relationship between Student and Course. This makes sense since a student can take many courses and a course can have many students.

### CODE REVIEW

**Comment by mel-quark** [comment]
it looks to me like enrollment is a join table for students and courses, which would mean that enrollment has_one student, and has_one course.

**Comment by CMUboy** [comment]
Yes, Enrollment is a join table, so you're right that it has_one student and has_one course. There can be many Enrollment records, however, so this allows a student to take many courses and a course to have many students.

```
 On Saturday, May 9, 2015 11:42 PM, Mel Quark <notifications@github.com> wrote:
```

 it looks to me like enrollment is a join table for students and courses, which would mean that enrollment has_one student, and has_once course.—

**Comment by mel-quark** [comment]
so, that means that a student has_many courses, :through enrollments
http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by CMUboy** [comment]
Yup. I guess I should change the diagram to make this relationship clearer. 

```
 On Sunday, May 10, 2015 5:19 PM, Mel Quark <notifications@github.com> wrote:
```

 so, that means that a student has_many courses, :through enrollments
http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association—

**Comment by CMUboy** [comment]
Yup. This is exactly what I wanted. The has_many :through relationship.

```
 On Sunday, May 10, 2015 5:19 PM, Mel Quark <notifications@github.com> wrote:
```

 so, that means that a student has_many courses, :through enrollments
http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association—

**Pull request merged**
